version: "3.9"

services:
  lbs:
    build: .
    container_name: lbs_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
